/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface GmUiBreadcrumbs {}
  interface GmUiBreadcrumbsAttributes extends StencilHTMLAttributes {}

  interface GmUiButton {}
  interface GmUiButtonAttributes extends StencilHTMLAttributes {}

  interface GmUiReadout {}
  interface GmUiReadoutAttributes extends StencilHTMLAttributes {}

  interface GmUiSpinner {}
  interface GmUiSpinnerAttributes extends StencilHTMLAttributes {}

  interface GmUiTab {}
  interface GmUiTabAttributes extends StencilHTMLAttributes {}

  interface GmUiTable {}
  interface GmUiTableAttributes extends StencilHTMLAttributes {}

  interface GmUiTooltip {}
  interface GmUiTooltipAttributes extends StencilHTMLAttributes {}

  interface GmUiAppFooter {}
  interface GmUiAppFooterAttributes extends StencilHTMLAttributes {}

  interface GmUiAppHeader {}
  interface GmUiAppHeaderAttributes extends StencilHTMLAttributes {}

  interface GmUiButtonGroup {}
  interface GmUiButtonGroupAttributes extends StencilHTMLAttributes {}

  interface GmUiErrorCard {
    'errorMsg': string;
    'icon': any;
  }
  interface GmUiErrorCardAttributes extends StencilHTMLAttributes {
    'errorMsg'?: string;
    'icon'?: any;
  }

  interface GmUiFieldset {}
  interface GmUiFieldsetAttributes extends StencilHTMLAttributes {}

  interface GmUiInputBox {}
  interface GmUiInputBoxAttributes extends StencilHTMLAttributes {}

  interface GmUiInputHint {}
  interface GmUiInputHintAttributes extends StencilHTMLAttributes {}

  interface GmUiInputLabel {}
  interface GmUiInputLabelAttributes extends StencilHTMLAttributes {}

  interface GmUiInputText {}
  interface GmUiInputTextAttributes extends StencilHTMLAttributes {}

  interface GmUiInputWrap {}
  interface GmUiInputWrapAttributes extends StencilHTMLAttributes {}

  interface GmUiTextArea {}
  interface GmUiTextAreaAttributes extends StencilHTMLAttributes {}

  interface GmUiCheckbox {}
  interface GmUiCheckboxAttributes extends StencilHTMLAttributes {}

  interface GmUiInputField {}
  interface GmUiInputFieldAttributes extends StencilHTMLAttributes {}

  interface GmUiInputRange {}
  interface GmUiInputRangeAttributes extends StencilHTMLAttributes {}

  interface GmUiRadio {}
  interface GmUiRadioAttributes extends StencilHTMLAttributes {}

  interface GmUiSelect {}
  interface GmUiSelectAttributes extends StencilHTMLAttributes {}

  interface GmUiTextarea {}
  interface GmUiTextareaAttributes extends StencilHTMLAttributes {}

  interface GmUiLayoutSection {
    'childEls': HTMLElement;
    'icon': Function;
    'sectionTitle': string;
  }
  interface GmUiLayoutSectionAttributes extends StencilHTMLAttributes {
    'childEls'?: HTMLElement;
    'icon'?: Function;
    'sectionTitle'?: string;
  }

  interface GmUiNavCardGroup {}
  interface GmUiNavCardGroupAttributes extends StencilHTMLAttributes {}

  interface GmUiNavCard {}
  interface GmUiNavCardAttributes extends StencilHTMLAttributes {}

  interface GmUiReadoutGroup {}
  interface GmUiReadoutGroupAttributes extends StencilHTMLAttributes {}

  interface GmUiTabGroup {}
  interface GmUiTabGroupAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'GmUiBreadcrumbs': Components.GmUiBreadcrumbs;
    'GmUiButton': Components.GmUiButton;
    'GmUiReadout': Components.GmUiReadout;
    'GmUiSpinner': Components.GmUiSpinner;
    'GmUiTab': Components.GmUiTab;
    'GmUiTable': Components.GmUiTable;
    'GmUiTooltip': Components.GmUiTooltip;
    'GmUiAppFooter': Components.GmUiAppFooter;
    'GmUiAppHeader': Components.GmUiAppHeader;
    'GmUiButtonGroup': Components.GmUiButtonGroup;
    'GmUiErrorCard': Components.GmUiErrorCard;
    'GmUiFieldset': Components.GmUiFieldset;
    'GmUiInputBox': Components.GmUiInputBox;
    'GmUiInputHint': Components.GmUiInputHint;
    'GmUiInputLabel': Components.GmUiInputLabel;
    'GmUiInputText': Components.GmUiInputText;
    'GmUiInputWrap': Components.GmUiInputWrap;
    'GmUiTextArea': Components.GmUiTextArea;
    'GmUiCheckbox': Components.GmUiCheckbox;
    'GmUiInputField': Components.GmUiInputField;
    'GmUiInputRange': Components.GmUiInputRange;
    'GmUiRadio': Components.GmUiRadio;
    'GmUiSelect': Components.GmUiSelect;
    'GmUiTextarea': Components.GmUiTextarea;
    'GmUiLayoutSection': Components.GmUiLayoutSection;
    'GmUiNavCardGroup': Components.GmUiNavCardGroup;
    'GmUiNavCard': Components.GmUiNavCard;
    'GmUiReadoutGroup': Components.GmUiReadoutGroup;
    'GmUiTabGroup': Components.GmUiTabGroup;
  }

  interface StencilIntrinsicElements {
    'gm-ui-breadcrumbs': Components.GmUiBreadcrumbsAttributes;
    'gm-ui-button': Components.GmUiButtonAttributes;
    'gm-ui-readout': Components.GmUiReadoutAttributes;
    'gm-ui-spinner': Components.GmUiSpinnerAttributes;
    'gm-ui-tab': Components.GmUiTabAttributes;
    'gm-ui-table': Components.GmUiTableAttributes;
    'gm-ui-tooltip': Components.GmUiTooltipAttributes;
    'gm-ui-app-footer': Components.GmUiAppFooterAttributes;
    'gm-ui-app-header': Components.GmUiAppHeaderAttributes;
    'gm-ui-button-group': Components.GmUiButtonGroupAttributes;
    'gm-ui-error-card': Components.GmUiErrorCardAttributes;
    'gm-ui-fieldset': Components.GmUiFieldsetAttributes;
    'gm-ui-input-box': Components.GmUiInputBoxAttributes;
    'gm-ui-input-hint': Components.GmUiInputHintAttributes;
    'gm-ui-input-label': Components.GmUiInputLabelAttributes;
    'gm-ui-input-text': Components.GmUiInputTextAttributes;
    'gm-ui-input-wrap': Components.GmUiInputWrapAttributes;
    'gm-ui-text-area': Components.GmUiTextAreaAttributes;
    'gm-ui-checkbox': Components.GmUiCheckboxAttributes;
    'gm-ui-input-field': Components.GmUiInputFieldAttributes;
    'gm-ui-input-range': Components.GmUiInputRangeAttributes;
    'gm-ui-radio': Components.GmUiRadioAttributes;
    'gm-ui-select': Components.GmUiSelectAttributes;
    'gm-ui-textarea': Components.GmUiTextareaAttributes;
    'gm-ui-layout-section': Components.GmUiLayoutSectionAttributes;
    'gm-ui-nav-card-group': Components.GmUiNavCardGroupAttributes;
    'gm-ui-nav-card': Components.GmUiNavCardAttributes;
    'gm-ui-readout-group': Components.GmUiReadoutGroupAttributes;
    'gm-ui-tab-group': Components.GmUiTabGroupAttributes;
  }


  interface HTMLGmUiBreadcrumbsElement extends Components.GmUiBreadcrumbs, HTMLStencilElement {}
  var HTMLGmUiBreadcrumbsElement: {
    prototype: HTMLGmUiBreadcrumbsElement;
    new (): HTMLGmUiBreadcrumbsElement;
  };

  interface HTMLGmUiButtonElement extends Components.GmUiButton, HTMLStencilElement {}
  var HTMLGmUiButtonElement: {
    prototype: HTMLGmUiButtonElement;
    new (): HTMLGmUiButtonElement;
  };

  interface HTMLGmUiReadoutElement extends Components.GmUiReadout, HTMLStencilElement {}
  var HTMLGmUiReadoutElement: {
    prototype: HTMLGmUiReadoutElement;
    new (): HTMLGmUiReadoutElement;
  };

  interface HTMLGmUiSpinnerElement extends Components.GmUiSpinner, HTMLStencilElement {}
  var HTMLGmUiSpinnerElement: {
    prototype: HTMLGmUiSpinnerElement;
    new (): HTMLGmUiSpinnerElement;
  };

  interface HTMLGmUiTabElement extends Components.GmUiTab, HTMLStencilElement {}
  var HTMLGmUiTabElement: {
    prototype: HTMLGmUiTabElement;
    new (): HTMLGmUiTabElement;
  };

  interface HTMLGmUiTableElement extends Components.GmUiTable, HTMLStencilElement {}
  var HTMLGmUiTableElement: {
    prototype: HTMLGmUiTableElement;
    new (): HTMLGmUiTableElement;
  };

  interface HTMLGmUiTooltipElement extends Components.GmUiTooltip, HTMLStencilElement {}
  var HTMLGmUiTooltipElement: {
    prototype: HTMLGmUiTooltipElement;
    new (): HTMLGmUiTooltipElement;
  };

  interface HTMLGmUiAppFooterElement extends Components.GmUiAppFooter, HTMLStencilElement {}
  var HTMLGmUiAppFooterElement: {
    prototype: HTMLGmUiAppFooterElement;
    new (): HTMLGmUiAppFooterElement;
  };

  interface HTMLGmUiAppHeaderElement extends Components.GmUiAppHeader, HTMLStencilElement {}
  var HTMLGmUiAppHeaderElement: {
    prototype: HTMLGmUiAppHeaderElement;
    new (): HTMLGmUiAppHeaderElement;
  };

  interface HTMLGmUiButtonGroupElement extends Components.GmUiButtonGroup, HTMLStencilElement {}
  var HTMLGmUiButtonGroupElement: {
    prototype: HTMLGmUiButtonGroupElement;
    new (): HTMLGmUiButtonGroupElement;
  };

  interface HTMLGmUiErrorCardElement extends Components.GmUiErrorCard, HTMLStencilElement {}
  var HTMLGmUiErrorCardElement: {
    prototype: HTMLGmUiErrorCardElement;
    new (): HTMLGmUiErrorCardElement;
  };

  interface HTMLGmUiFieldsetElement extends Components.GmUiFieldset, HTMLStencilElement {}
  var HTMLGmUiFieldsetElement: {
    prototype: HTMLGmUiFieldsetElement;
    new (): HTMLGmUiFieldsetElement;
  };

  interface HTMLGmUiInputBoxElement extends Components.GmUiInputBox, HTMLStencilElement {}
  var HTMLGmUiInputBoxElement: {
    prototype: HTMLGmUiInputBoxElement;
    new (): HTMLGmUiInputBoxElement;
  };

  interface HTMLGmUiInputHintElement extends Components.GmUiInputHint, HTMLStencilElement {}
  var HTMLGmUiInputHintElement: {
    prototype: HTMLGmUiInputHintElement;
    new (): HTMLGmUiInputHintElement;
  };

  interface HTMLGmUiInputLabelElement extends Components.GmUiInputLabel, HTMLStencilElement {}
  var HTMLGmUiInputLabelElement: {
    prototype: HTMLGmUiInputLabelElement;
    new (): HTMLGmUiInputLabelElement;
  };

  interface HTMLGmUiInputTextElement extends Components.GmUiInputText, HTMLStencilElement {}
  var HTMLGmUiInputTextElement: {
    prototype: HTMLGmUiInputTextElement;
    new (): HTMLGmUiInputTextElement;
  };

  interface HTMLGmUiInputWrapElement extends Components.GmUiInputWrap, HTMLStencilElement {}
  var HTMLGmUiInputWrapElement: {
    prototype: HTMLGmUiInputWrapElement;
    new (): HTMLGmUiInputWrapElement;
  };

  interface HTMLGmUiTextAreaElement extends Components.GmUiTextArea, HTMLStencilElement {}
  var HTMLGmUiTextAreaElement: {
    prototype: HTMLGmUiTextAreaElement;
    new (): HTMLGmUiTextAreaElement;
  };

  interface HTMLGmUiCheckboxElement extends Components.GmUiCheckbox, HTMLStencilElement {}
  var HTMLGmUiCheckboxElement: {
    prototype: HTMLGmUiCheckboxElement;
    new (): HTMLGmUiCheckboxElement;
  };

  interface HTMLGmUiInputFieldElement extends Components.GmUiInputField, HTMLStencilElement {}
  var HTMLGmUiInputFieldElement: {
    prototype: HTMLGmUiInputFieldElement;
    new (): HTMLGmUiInputFieldElement;
  };

  interface HTMLGmUiInputRangeElement extends Components.GmUiInputRange, HTMLStencilElement {}
  var HTMLGmUiInputRangeElement: {
    prototype: HTMLGmUiInputRangeElement;
    new (): HTMLGmUiInputRangeElement;
  };

  interface HTMLGmUiRadioElement extends Components.GmUiRadio, HTMLStencilElement {}
  var HTMLGmUiRadioElement: {
    prototype: HTMLGmUiRadioElement;
    new (): HTMLGmUiRadioElement;
  };

  interface HTMLGmUiSelectElement extends Components.GmUiSelect, HTMLStencilElement {}
  var HTMLGmUiSelectElement: {
    prototype: HTMLGmUiSelectElement;
    new (): HTMLGmUiSelectElement;
  };

  interface HTMLGmUiTextareaElement extends Components.GmUiTextarea, HTMLStencilElement {}
  var HTMLGmUiTextareaElement: {
    prototype: HTMLGmUiTextareaElement;
    new (): HTMLGmUiTextareaElement;
  };

  interface HTMLGmUiLayoutSectionElement extends Components.GmUiLayoutSection, HTMLStencilElement {}
  var HTMLGmUiLayoutSectionElement: {
    prototype: HTMLGmUiLayoutSectionElement;
    new (): HTMLGmUiLayoutSectionElement;
  };

  interface HTMLGmUiNavCardGroupElement extends Components.GmUiNavCardGroup, HTMLStencilElement {}
  var HTMLGmUiNavCardGroupElement: {
    prototype: HTMLGmUiNavCardGroupElement;
    new (): HTMLGmUiNavCardGroupElement;
  };

  interface HTMLGmUiNavCardElement extends Components.GmUiNavCard, HTMLStencilElement {}
  var HTMLGmUiNavCardElement: {
    prototype: HTMLGmUiNavCardElement;
    new (): HTMLGmUiNavCardElement;
  };

  interface HTMLGmUiReadoutGroupElement extends Components.GmUiReadoutGroup, HTMLStencilElement {}
  var HTMLGmUiReadoutGroupElement: {
    prototype: HTMLGmUiReadoutGroupElement;
    new (): HTMLGmUiReadoutGroupElement;
  };

  interface HTMLGmUiTabGroupElement extends Components.GmUiTabGroup, HTMLStencilElement {}
  var HTMLGmUiTabGroupElement: {
    prototype: HTMLGmUiTabGroupElement;
    new (): HTMLGmUiTabGroupElement;
  };

  interface HTMLElementTagNameMap {
    'gm-ui-breadcrumbs': HTMLGmUiBreadcrumbsElement
    'gm-ui-button': HTMLGmUiButtonElement
    'gm-ui-readout': HTMLGmUiReadoutElement
    'gm-ui-spinner': HTMLGmUiSpinnerElement
    'gm-ui-tab': HTMLGmUiTabElement
    'gm-ui-table': HTMLGmUiTableElement
    'gm-ui-tooltip': HTMLGmUiTooltipElement
    'gm-ui-app-footer': HTMLGmUiAppFooterElement
    'gm-ui-app-header': HTMLGmUiAppHeaderElement
    'gm-ui-button-group': HTMLGmUiButtonGroupElement
    'gm-ui-error-card': HTMLGmUiErrorCardElement
    'gm-ui-fieldset': HTMLGmUiFieldsetElement
    'gm-ui-input-box': HTMLGmUiInputBoxElement
    'gm-ui-input-hint': HTMLGmUiInputHintElement
    'gm-ui-input-label': HTMLGmUiInputLabelElement
    'gm-ui-input-text': HTMLGmUiInputTextElement
    'gm-ui-input-wrap': HTMLGmUiInputWrapElement
    'gm-ui-text-area': HTMLGmUiTextAreaElement
    'gm-ui-checkbox': HTMLGmUiCheckboxElement
    'gm-ui-input-field': HTMLGmUiInputFieldElement
    'gm-ui-input-range': HTMLGmUiInputRangeElement
    'gm-ui-radio': HTMLGmUiRadioElement
    'gm-ui-select': HTMLGmUiSelectElement
    'gm-ui-textarea': HTMLGmUiTextareaElement
    'gm-ui-layout-section': HTMLGmUiLayoutSectionElement
    'gm-ui-nav-card-group': HTMLGmUiNavCardGroupElement
    'gm-ui-nav-card': HTMLGmUiNavCardElement
    'gm-ui-readout-group': HTMLGmUiReadoutGroupElement
    'gm-ui-tab-group': HTMLGmUiTabGroupElement
  }

  interface ElementTagNameMap {
    'gm-ui-breadcrumbs': HTMLGmUiBreadcrumbsElement;
    'gm-ui-button': HTMLGmUiButtonElement;
    'gm-ui-readout': HTMLGmUiReadoutElement;
    'gm-ui-spinner': HTMLGmUiSpinnerElement;
    'gm-ui-tab': HTMLGmUiTabElement;
    'gm-ui-table': HTMLGmUiTableElement;
    'gm-ui-tooltip': HTMLGmUiTooltipElement;
    'gm-ui-app-footer': HTMLGmUiAppFooterElement;
    'gm-ui-app-header': HTMLGmUiAppHeaderElement;
    'gm-ui-button-group': HTMLGmUiButtonGroupElement;
    'gm-ui-error-card': HTMLGmUiErrorCardElement;
    'gm-ui-fieldset': HTMLGmUiFieldsetElement;
    'gm-ui-input-box': HTMLGmUiInputBoxElement;
    'gm-ui-input-hint': HTMLGmUiInputHintElement;
    'gm-ui-input-label': HTMLGmUiInputLabelElement;
    'gm-ui-input-text': HTMLGmUiInputTextElement;
    'gm-ui-input-wrap': HTMLGmUiInputWrapElement;
    'gm-ui-text-area': HTMLGmUiTextAreaElement;
    'gm-ui-checkbox': HTMLGmUiCheckboxElement;
    'gm-ui-input-field': HTMLGmUiInputFieldElement;
    'gm-ui-input-range': HTMLGmUiInputRangeElement;
    'gm-ui-radio': HTMLGmUiRadioElement;
    'gm-ui-select': HTMLGmUiSelectElement;
    'gm-ui-textarea': HTMLGmUiTextareaElement;
    'gm-ui-layout-section': HTMLGmUiLayoutSectionElement;
    'gm-ui-nav-card-group': HTMLGmUiNavCardGroupElement;
    'gm-ui-nav-card': HTMLGmUiNavCardElement;
    'gm-ui-readout-group': HTMLGmUiReadoutGroupElement;
    'gm-ui-tab-group': HTMLGmUiTabGroupElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
