/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface GmUiAppFooter {}
  interface GmUiAppFooterAttributes extends StencilHTMLAttributes {}

  interface GmUiAppHeader {}
  interface GmUiAppHeaderAttributes extends StencilHTMLAttributes {}

  interface GmUiBreadcrumbs {}
  interface GmUiBreadcrumbsAttributes extends StencilHTMLAttributes {}

  interface GmUiButtonGroup {}
  interface GmUiButtonGroupAttributes extends StencilHTMLAttributes {}

  interface GmUiButton {}
  interface GmUiButtonAttributes extends StencilHTMLAttributes {}

  interface GmUiErrorCard {}
  interface GmUiErrorCardAttributes extends StencilHTMLAttributes {}

  interface GmUiLayoutSection {}
  interface GmUiLayoutSectionAttributes extends StencilHTMLAttributes {}

  interface GmUiNavCardGroup {}
  interface GmUiNavCardGroupAttributes extends StencilHTMLAttributes {}

  interface GmUiNavCard {}
  interface GmUiNavCardAttributes extends StencilHTMLAttributes {}

  interface GmUiReadoutGroup {}
  interface GmUiReadoutGroupAttributes extends StencilHTMLAttributes {}

  interface GmUiReadout {}
  interface GmUiReadoutAttributes extends StencilHTMLAttributes {}

  interface GmUiSpinner {}
  interface GmUiSpinnerAttributes extends StencilHTMLAttributes {}

  interface GmUiTabGroup {}
  interface GmUiTabGroupAttributes extends StencilHTMLAttributes {}

  interface GmUiTab {}
  interface GmUiTabAttributes extends StencilHTMLAttributes {}

  interface GmUiTable {}
  interface GmUiTableAttributes extends StencilHTMLAttributes {}

  interface GmUiTooltip {}
  interface GmUiTooltipAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'GmUiAppFooter': Components.GmUiAppFooter;
    'GmUiAppHeader': Components.GmUiAppHeader;
    'GmUiBreadcrumbs': Components.GmUiBreadcrumbs;
    'GmUiButtonGroup': Components.GmUiButtonGroup;
    'GmUiButton': Components.GmUiButton;
    'GmUiErrorCard': Components.GmUiErrorCard;
    'GmUiLayoutSection': Components.GmUiLayoutSection;
    'GmUiNavCardGroup': Components.GmUiNavCardGroup;
    'GmUiNavCard': Components.GmUiNavCard;
    'GmUiReadoutGroup': Components.GmUiReadoutGroup;
    'GmUiReadout': Components.GmUiReadout;
    'GmUiSpinner': Components.GmUiSpinner;
    'GmUiTabGroup': Components.GmUiTabGroup;
    'GmUiTab': Components.GmUiTab;
    'GmUiTable': Components.GmUiTable;
    'GmUiTooltip': Components.GmUiTooltip;
  }

  interface StencilIntrinsicElements {
    'gm-ui-app-footer': Components.GmUiAppFooterAttributes;
    'gm-ui-app-header': Components.GmUiAppHeaderAttributes;
    'gm-ui-breadcrumbs': Components.GmUiBreadcrumbsAttributes;
    'gm-ui-button-group': Components.GmUiButtonGroupAttributes;
    'gm-ui-button': Components.GmUiButtonAttributes;
    'gm-ui-error-card': Components.GmUiErrorCardAttributes;
    'gm-ui-layout-section': Components.GmUiLayoutSectionAttributes;
    'gm-ui-nav-card-group': Components.GmUiNavCardGroupAttributes;
    'gm-ui-nav-card': Components.GmUiNavCardAttributes;
    'gm-ui-readout-group': Components.GmUiReadoutGroupAttributes;
    'gm-ui-readout': Components.GmUiReadoutAttributes;
    'gm-ui-spinner': Components.GmUiSpinnerAttributes;
    'gm-ui-tab-group': Components.GmUiTabGroupAttributes;
    'gm-ui-tab': Components.GmUiTabAttributes;
    'gm-ui-table': Components.GmUiTableAttributes;
    'gm-ui-tooltip': Components.GmUiTooltipAttributes;
  }


  interface HTMLGmUiAppFooterElement extends Components.GmUiAppFooter, HTMLStencilElement {}
  var HTMLGmUiAppFooterElement: {
    prototype: HTMLGmUiAppFooterElement;
    new (): HTMLGmUiAppFooterElement;
  };

  interface HTMLGmUiAppHeaderElement extends Components.GmUiAppHeader, HTMLStencilElement {}
  var HTMLGmUiAppHeaderElement: {
    prototype: HTMLGmUiAppHeaderElement;
    new (): HTMLGmUiAppHeaderElement;
  };

  interface HTMLGmUiBreadcrumbsElement extends Components.GmUiBreadcrumbs, HTMLStencilElement {}
  var HTMLGmUiBreadcrumbsElement: {
    prototype: HTMLGmUiBreadcrumbsElement;
    new (): HTMLGmUiBreadcrumbsElement;
  };

  interface HTMLGmUiButtonGroupElement extends Components.GmUiButtonGroup, HTMLStencilElement {}
  var HTMLGmUiButtonGroupElement: {
    prototype: HTMLGmUiButtonGroupElement;
    new (): HTMLGmUiButtonGroupElement;
  };

  interface HTMLGmUiButtonElement extends Components.GmUiButton, HTMLStencilElement {}
  var HTMLGmUiButtonElement: {
    prototype: HTMLGmUiButtonElement;
    new (): HTMLGmUiButtonElement;
  };

  interface HTMLGmUiErrorCardElement extends Components.GmUiErrorCard, HTMLStencilElement {}
  var HTMLGmUiErrorCardElement: {
    prototype: HTMLGmUiErrorCardElement;
    new (): HTMLGmUiErrorCardElement;
  };

  interface HTMLGmUiLayoutSectionElement extends Components.GmUiLayoutSection, HTMLStencilElement {}
  var HTMLGmUiLayoutSectionElement: {
    prototype: HTMLGmUiLayoutSectionElement;
    new (): HTMLGmUiLayoutSectionElement;
  };

  interface HTMLGmUiNavCardGroupElement extends Components.GmUiNavCardGroup, HTMLStencilElement {}
  var HTMLGmUiNavCardGroupElement: {
    prototype: HTMLGmUiNavCardGroupElement;
    new (): HTMLGmUiNavCardGroupElement;
  };

  interface HTMLGmUiNavCardElement extends Components.GmUiNavCard, HTMLStencilElement {}
  var HTMLGmUiNavCardElement: {
    prototype: HTMLGmUiNavCardElement;
    new (): HTMLGmUiNavCardElement;
  };

  interface HTMLGmUiReadoutGroupElement extends Components.GmUiReadoutGroup, HTMLStencilElement {}
  var HTMLGmUiReadoutGroupElement: {
    prototype: HTMLGmUiReadoutGroupElement;
    new (): HTMLGmUiReadoutGroupElement;
  };

  interface HTMLGmUiReadoutElement extends Components.GmUiReadout, HTMLStencilElement {}
  var HTMLGmUiReadoutElement: {
    prototype: HTMLGmUiReadoutElement;
    new (): HTMLGmUiReadoutElement;
  };

  interface HTMLGmUiSpinnerElement extends Components.GmUiSpinner, HTMLStencilElement {}
  var HTMLGmUiSpinnerElement: {
    prototype: HTMLGmUiSpinnerElement;
    new (): HTMLGmUiSpinnerElement;
  };

  interface HTMLGmUiTabGroupElement extends Components.GmUiTabGroup, HTMLStencilElement {}
  var HTMLGmUiTabGroupElement: {
    prototype: HTMLGmUiTabGroupElement;
    new (): HTMLGmUiTabGroupElement;
  };

  interface HTMLGmUiTabElement extends Components.GmUiTab, HTMLStencilElement {}
  var HTMLGmUiTabElement: {
    prototype: HTMLGmUiTabElement;
    new (): HTMLGmUiTabElement;
  };

  interface HTMLGmUiTableElement extends Components.GmUiTable, HTMLStencilElement {}
  var HTMLGmUiTableElement: {
    prototype: HTMLGmUiTableElement;
    new (): HTMLGmUiTableElement;
  };

  interface HTMLGmUiTooltipElement extends Components.GmUiTooltip, HTMLStencilElement {}
  var HTMLGmUiTooltipElement: {
    prototype: HTMLGmUiTooltipElement;
    new (): HTMLGmUiTooltipElement;
  };

  interface HTMLElementTagNameMap {
    'gm-ui-app-footer': HTMLGmUiAppFooterElement
    'gm-ui-app-header': HTMLGmUiAppHeaderElement
    'gm-ui-breadcrumbs': HTMLGmUiBreadcrumbsElement
    'gm-ui-button-group': HTMLGmUiButtonGroupElement
    'gm-ui-button': HTMLGmUiButtonElement
    'gm-ui-error-card': HTMLGmUiErrorCardElement
    'gm-ui-layout-section': HTMLGmUiLayoutSectionElement
    'gm-ui-nav-card-group': HTMLGmUiNavCardGroupElement
    'gm-ui-nav-card': HTMLGmUiNavCardElement
    'gm-ui-readout-group': HTMLGmUiReadoutGroupElement
    'gm-ui-readout': HTMLGmUiReadoutElement
    'gm-ui-spinner': HTMLGmUiSpinnerElement
    'gm-ui-tab-group': HTMLGmUiTabGroupElement
    'gm-ui-tab': HTMLGmUiTabElement
    'gm-ui-table': HTMLGmUiTableElement
    'gm-ui-tooltip': HTMLGmUiTooltipElement
  }

  interface ElementTagNameMap {
    'gm-ui-app-footer': HTMLGmUiAppFooterElement;
    'gm-ui-app-header': HTMLGmUiAppHeaderElement;
    'gm-ui-breadcrumbs': HTMLGmUiBreadcrumbsElement;
    'gm-ui-button-group': HTMLGmUiButtonGroupElement;
    'gm-ui-button': HTMLGmUiButtonElement;
    'gm-ui-error-card': HTMLGmUiErrorCardElement;
    'gm-ui-layout-section': HTMLGmUiLayoutSectionElement;
    'gm-ui-nav-card-group': HTMLGmUiNavCardGroupElement;
    'gm-ui-nav-card': HTMLGmUiNavCardElement;
    'gm-ui-readout-group': HTMLGmUiReadoutGroupElement;
    'gm-ui-readout': HTMLGmUiReadoutElement;
    'gm-ui-spinner': HTMLGmUiSpinnerElement;
    'gm-ui-tab-group': HTMLGmUiTabGroupElement;
    'gm-ui-tab': HTMLGmUiTabElement;
    'gm-ui-table': HTMLGmUiTableElement;
    'gm-ui-tooltip': HTMLGmUiTooltipElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
